import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900 min-h-screen flex flex-col">
        <header className="bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between">
          <span className="font-bold text-lg tracking-tight">
            FactoryFlow Planner
          </span>
          <nav className="flex space-x-4 text-sm font-medium">
            <Link href="/" className="text-blue-600 hover:underline">
              Availability Grid
            </Link>
            <Link
              href="/schedule"
              className="text-gray-600 hover:text-blue-600"
            >
              Schedule Order
            </Link>
          </nav>
        </header>
        <div className="flex-1 overflow-auto">{children}</div>
      </body>
    </html>
  );
}
